
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  host: localhost

development:
  <<: *default
  database: speakerinnen_development

test:
  <<: *default
  database: speakerinnen_test

staging:
  <<: *default
  database: YOUR-DATABASE-NAME
  password: YOUR-DATABASE-USERNAME-PASSWORD

production:
  <<: *default
  database: YOUR-DATABASE-NAME
  password: YOUR-DATABASE-USERNAME-PASSWORD
